// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tn.industry.domain;

import com.tn.industry.domain.ActivityBranch;
import com.tn.industry.domain.ActivityBranchDataOnDemand;
import com.tn.industry.domain.SectorDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ActivityBranchDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ActivityBranchDataOnDemand: @Component;
    
    private Random ActivityBranchDataOnDemand.rnd = new SecureRandom();
    
    private List<ActivityBranch> ActivityBranchDataOnDemand.data;
    
    @Autowired
    private SectorDataOnDemand ActivityBranchDataOnDemand.sectorDataOnDemand;
    
    public ActivityBranch ActivityBranchDataOnDemand.getNewTransientActivityBranch(int index) {
        ActivityBranch obj = new ActivityBranch();
        setActivityName(obj, index);
        return obj;
    }
    
    public void ActivityBranchDataOnDemand.setActivityName(ActivityBranch obj, int index) {
        String activityName = "activityName_" + index;
        obj.setActivityName(activityName);
    }
    
    public ActivityBranch ActivityBranchDataOnDemand.getSpecificActivityBranch(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ActivityBranch obj = data.get(index);
        Long id = obj.getId();
        return ActivityBranch.findActivityBranch(id);
    }
    
    public ActivityBranch ActivityBranchDataOnDemand.getRandomActivityBranch() {
        init();
        ActivityBranch obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ActivityBranch.findActivityBranch(id);
    }
    
    public boolean ActivityBranchDataOnDemand.modifyActivityBranch(ActivityBranch obj) {
        return false;
    }
    
    public void ActivityBranchDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ActivityBranch.findActivityBranchEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ActivityBranch' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ActivityBranch>();
        for (int i = 0; i < 10; i++) {
            ActivityBranch obj = getNewTransientActivityBranch(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
