// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tn.industry.domain;

import com.tn.industry.domain.ProductsIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ProductsIntegrationTest_Roo_Configurable {
    
    declare @type: ProductsIntegrationTest: @Configurable;
    
}
