// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tn.industry.domain;

import com.tn.industry.domain.ActivityBranchDataOnDemand;
import com.tn.industry.domain.Products;
import com.tn.industry.domain.ProductsDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ProductsDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProductsDataOnDemand: @Component;
    
    private Random ProductsDataOnDemand.rnd = new SecureRandom();
    
    private List<Products> ProductsDataOnDemand.data;
    
    @Autowired
    private ActivityBranchDataOnDemand ProductsDataOnDemand.activityBranchDataOnDemand;
    
    public Products ProductsDataOnDemand.getNewTransientProducts(int index) {
        Products obj = new Products();
        setProductsName(obj, index);
        return obj;
    }
    
    public void ProductsDataOnDemand.setProductsName(Products obj, int index) {
        String productsName = "productsName_" + index;
        obj.setProductsName(productsName);
    }
    
    public Products ProductsDataOnDemand.getSpecificProducts(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Products obj = data.get(index);
        Long id = obj.getId();
        return Products.findProducts(id);
    }
    
    public Products ProductsDataOnDemand.getRandomProducts() {
        init();
        Products obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Products.findProducts(id);
    }
    
    public boolean ProductsDataOnDemand.modifyProducts(Products obj) {
        return false;
    }
    
    public void ProductsDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Products.findProductsEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Products' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Products>();
        for (int i = 0; i < 10; i++) {
            Products obj = getNewTransientProducts(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
