// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tn.industry.domain;

import com.tn.industry.domain.Products;
import com.tn.industry.domain.ProductsDataOnDemand;
import com.tn.industry.domain.ProductsIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProductsIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProductsIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProductsIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ProductsIntegrationTest: @Transactional;
    
    @Autowired
    private ProductsDataOnDemand ProductsIntegrationTest.dod;
    
    @Test
    public void ProductsIntegrationTest.testCountProductses() {
        Assert.assertNotNull("Data on demand for 'Products' failed to initialize correctly", dod.getRandomProducts());
        long count = Products.countProductses();
        Assert.assertTrue("Counter for 'Products' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProductsIntegrationTest.testFindProducts() {
        Products obj = dod.getRandomProducts();
        Assert.assertNotNull("Data on demand for 'Products' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Products' failed to provide an identifier", id);
        obj = Products.findProducts(id);
        Assert.assertNotNull("Find method for 'Products' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Products' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProductsIntegrationTest.testFindAllProductses() {
        Assert.assertNotNull("Data on demand for 'Products' failed to initialize correctly", dod.getRandomProducts());
        long count = Products.countProductses();
        Assert.assertTrue("Too expensive to perform a find all test for 'Products', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Products> result = Products.findAllProductses();
        Assert.assertNotNull("Find all method for 'Products' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Products' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProductsIntegrationTest.testFindProductsEntries() {
        Assert.assertNotNull("Data on demand for 'Products' failed to initialize correctly", dod.getRandomProducts());
        long count = Products.countProductses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Products> result = Products.findProductsEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Products' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Products' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProductsIntegrationTest.testFlush() {
        Products obj = dod.getRandomProducts();
        Assert.assertNotNull("Data on demand for 'Products' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Products' failed to provide an identifier", id);
        obj = Products.findProducts(id);
        Assert.assertNotNull("Find method for 'Products' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyProducts(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Products' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProductsIntegrationTest.testMergeUpdate() {
        Products obj = dod.getRandomProducts();
        Assert.assertNotNull("Data on demand for 'Products' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Products' failed to provide an identifier", id);
        obj = Products.findProducts(id);
        boolean modified =  dod.modifyProducts(obj);
        Integer currentVersion = obj.getVersion();
        Products merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Products' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProductsIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Products' failed to initialize correctly", dod.getRandomProducts());
        Products obj = dod.getNewTransientProducts(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Products' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Products' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Products' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ProductsIntegrationTest.testRemove() {
        Products obj = dod.getRandomProducts();
        Assert.assertNotNull("Data on demand for 'Products' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Products' failed to provide an identifier", id);
        obj = Products.findProducts(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Products' with identifier '" + id + "'", Products.findProducts(id));
    }
    
}
