// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tn.industry.domain;

import com.tn.industry.domain.Sector;
import com.tn.industry.domain.SectorDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect SectorDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SectorDataOnDemand: @Component;
    
    private Random SectorDataOnDemand.rnd = new SecureRandom();
    
    private List<Sector> SectorDataOnDemand.data;
    
    public Sector SectorDataOnDemand.getNewTransientSector(int index) {
        Sector obj = new Sector();
        setSectorName(obj, index);
        return obj;
    }
    
    public void SectorDataOnDemand.setSectorName(Sector obj, int index) {
        String sectorName = "sectorName_" + index;
        obj.setSectorName(sectorName);
    }
    
    public Sector SectorDataOnDemand.getSpecificSector(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Sector obj = data.get(index);
        Long id = obj.getId();
        return Sector.findSector(id);
    }
    
    public Sector SectorDataOnDemand.getRandomSector() {
        init();
        Sector obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Sector.findSector(id);
    }
    
    public boolean SectorDataOnDemand.modifySector(Sector obj) {
        return false;
    }
    
    public void SectorDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Sector.findSectorEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Sector' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Sector>();
        for (int i = 0; i < 10; i++) {
            Sector obj = getNewTransientSector(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
